# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDoOT2Y9lOTZLp1l9j8q3RuRM-692K4Q
"""

import pandas as pd

df = pd.read_csv('fake_job_postings.csv')
print(df.head())

print("Dataset Info:")
print(df.info())

print("Missing Values per Column:")
print(df.isnull().sum())

